name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Issue Check 101. Thank for reporting this issue. We will verify and update you shortly.'
        pr-message: 'Greetings on your pr. Thank your posting this pr. We will verify and update you shortly.'
